#文件绝对路径！！！
#数据集
path: D:\python123\ultralytics\datas
#训练集(相对path)
train: images/train
#验证集(相对path)
val: images/val

# Classes  分类
names:
  0: "井盖破损"
  1: "完整"
  2: "地面塌陷"
  3: "有物品覆盖井盖"
  4: "井盖位移"
  5: "井盖缺失"
